_vn_alphabets = 'aáàăắằẵẳặâấầẫẩậãảạbcdđeéèêếềễểệẽẻẹfghiíìĩỉịjklmnoóòôốồỗổộõỏọơớờỡởợpqrstuúùũủụưứừữửựvwxyýỳỹỷỵz'
_VN_ALPHABETS = 'AÁÀĂẮẰẴẲẶÂẤẦẪẨẬÃẢẠBCDĐEÉÈÊẾỀỄỂỆẼẺẸFGHIÍÌĨỈỊJKLMNOÓÒÔỐỒỖỔỘÕỎỌƠỚỜỠỞỢPQRSTUÚÙŨỦỤƯỨỪỮỬỰVWXYÝỲỸỶỴZ'

VN_ALPHABETS = _vn_alphabets + _VN_ALPHABETS